### ISSUE TITLE
Break apart some dependencies

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-config-api#1]
wildfly-config-api.jar ends up depending on -generator.jar, which then drags in wildfly-controller, wildfly-server (and everything that implies), along with roaster-jdt and eclipse-json bits.

If we could move annotations to a wildfly-config-runtime, and have -generator and -config-api both share, but not rely upon each other, that'd be cool af.

**Comment by lance** [comment]
Fixed in 0.3.0
