### ISSUE TITLE
Type inference error

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-config-api#11]
@bobmcwhirter Could this be related to your recent changes?

[ERROR] reason: inferred type does not conform to upper bound(s)
[ERROR] inferred: org.wildfly.swarm.config.infinispan.cache_container.CustomStore<capture#99 of ?>
[ERROR] upper bound(s): org.wildfly.swarm.config.infinispan.cache_container.CustomStore<org.wildfly.swarm.config.infinispan.cache_container.CustomStore<capture#99 of ?>>,org.wildfly.swarm.config.infinispan.cache_container.CustomStore<capture#99 of ?>
[ERROR] /Users/hbraun/dev/prj/wildfly-config-api/api/target/generated-sources/org/wildfly/swarm/config/infinispan/cache_container/LocalCache.java:[614,55] incompatible types: cannot infer type arguments for org.wildfly.swarm.config.infinispan.cache_container.CustomStore<>

**Comment by bobmcwhirter** [comment]
I saw that a lot but thought I got past it before I pushed. I'll look into
it.

--
Sent from my iPhone


On Nov 6, 2015, at 2:32 AM, Heiko Braun <notifications@github.com> wrote:

@bobmcwhirter <https://github.com/bobmcwhirter> Could this be related to
your recent changes?

[ERROR] reason: inferred type does not conform to upper bound(s)
[ERROR] inferred:
org.wildfly.swarm.config.infinispan.cache_container.CustomStore
[ERROR] upper bound(s):
org.wildfly.swarm.config.infinispan.cache_container.CustomStore>,org.wildfly.swarm.config.infinispan.cache_container.CustomStore
[ERROR]
/Users/hbraun/dev/prj/wildfly-config-api/api/target/generated-sources/org/wildfly/swarm/config/infinispan/cache_container/LocalCache.java:[614,55]
incompatible types: cannot infer type arguments for
org.wildfly.swarm.config.infinispan.cache_container.CustomStore<>

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-config-api/issues/11>.
