### ISSUE TITLE
Fix jgroups naming slightly better

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-config-api#14]
While I improved some name mangling to support stuff like `relay.RELAY2`, moving the prefix to the package, and keeping the class as all-caps, it still generates a method like:

    public T rELAY2(RELAY2 value) { ... }

since it apparently just down-cases the first letter when creating the method name.  I'm not certain the appropriate behaviour.  Either `relay2(...)` or `RELAY2(...)` but `rELAY2(..)` is absolutely wrong.

**Comment by heiko-braun** [comment]
Adding another leetspeak adapter would make it perfectly nerdy.

```
public T r37AY2(R37AY2 value) { ... }
```

**Comment by kenfinnigan** [comment]
Moved to https://issues.jboss.org/browse/SWARM-234
