### ISSUE TITLE
Reduce template usage for non-root classes

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-config-api#4]
Currently every generated class takes the form of

    public class Whatever<T extends Whatever> {...}

It'd be fine if that only occurred on roots (subclassed by WhateverFraction) and not necessarily all others.

**Comment by lance** [comment]
Just the root objects doesn't make sense anymore https://github.com/wildfly-swarm/wildfly-swarm/blob/master/datasources/api/src/main/java/org/wildfly/swarm/datasources/JdbcDriver.java#L6
