### ISSUE TITLE
Add support for property changes (and change sets)

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-config-api#5]
@ppalaga I've implemented the first support for change sets: https://github.com/heiko-braun/wildfly-config-api/blob/changesets/api/src/test/java/org/wildfly/swarm/config/IntegrationTestCase.java#L193

**Comment by heiko-braun** [comment]
In short, this code:

```
        DataSource dataSource = new DataSource("TestDS");
        dataSource.jndiName("java:/foo/bar/DS");
        dataSource.userName("john.doe");
        dataSource.password("password");

        Map<String, Object> changeset = new HashMap<>();
        dataSource.addPropertyChangeListener(evt -> {
            changeset.put(evt.getPropertyName(), evt.getNewValue());
        });

        dataSource.userName("john.doe2");
        dataSource.password("password2");

        EntityAdapter<DataSource> entityAdapter = new EntityAdapter<>(DataSource.class);
        ModelNode operation = entityAdapter.fromChangeset(changeset);
        // invoke on operation on server

```

produces a composite operation like:

```
{
    "operation" => "composite",
    "address" => [],
    "steps" => [
        {
            "address" => [
                ("subsystem" => "datasources"),
                ("data-source" => "*")
            ],
            "operation" => "write-attribute",
            "name" => "password",
            "value" => {"password" => "password2"}
        },
        {
            "address" => [
                ("subsystem" => "datasources"),
                ("data-source" => "*")
            ],
            "operation" => "write-attribute",
            "name" => "userName",
            "value" => {"user-name" => "john.doe2"}
        }
    ]
}
```

**Comment by ppalaga** [comment]
Great, thanks!

**Comment by heiko-braun** [comment]
This complements the API to read/write full resources on the EntitAdapter<T>: 

- https://github.com/heiko-braun/api-gen/blob/changesets/runtime/src/main/java/org/wildfly/config/invocation/EntityAdapter.java#L92

- https://github.com/heiko-braun/api-gen/blob/changesets/runtime/src/main/java/org/wildfly/config/invocation/EntityAdapter.java#L269

**Comment by heiko-braun** [comment]
@ppalaga let me know if this fits your purpose

**Comment by heiko-braun** [comment]
@lance This is a change request from hawkular. They intend to use the lib standalone to configure wildfly instances. Any objections if we merge this?

**Comment by heiko-braun** [comment]
@ppalaga did you have the time to look at it?

**Comment by ppalaga** [comment]
@heiko-braun sorry, not yet, we are releasing a hk milestone today.

**Comment by lance** [comment]
@heiko-braun I am ok with merging this. As an aside, it does feel odd that what is now the "canonical" repo for wildfly-config-api is a fork of yours, even though that's exactly how it happened.

**Comment by ppalaga** [comment]
@lance to avoid "fork of", @heiko-braun should "Transfer ownership" of his repo to wildfly-swarm.

**Comment by heiko-braun** [comment]
@lance yes, it's some weird github internal. I don't it to remain like this either, but then I have new clue how to fix. But we can try what @ppalaga suggested.

**Comment by heiko-braun** [comment]
Blocked by the decision how to move forward with #7 and #8
